name: Playwright-Elixir CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  all:
    name: Build & Test
    runs-on: ubuntu-20.04
    env:
      MIX_ENV: test
      PLAYWRIGHT_TRANSPORT: driver
    steps:
    - uses: actions/checkout@v2
    - name: Set up Elixir
      uses: erlef/setup-elixir@v1
      with:
        elixir-version: '1.16.2'
        otp-version: '26.2.5'
    - name: Install Elixir dependencies
      run: mix deps.get
    - name: Install Node dependencies
      run: npm install --prefix assets
    - name: Run tests
      run: mix test
